spring.application.name=GestionConge
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionconge
spring.datasource.username=postgres
spring.datasource.password=FRUVIO1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

logging.level.org.springframework.boot.autoconfigure=INFO

logging.level.org.springframework=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG

spring.jackson.date-format=yyyy-MM-dd

spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG
debug=true

server.error.include-stacktrace=always
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG

# Configuration pour Gmail SMTP (Exemple)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=votre-adresse-gmail@gmail.com
spring.mail.password=votre_mot_de_passe_d_application
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true